- name: Copy files from backend
  become: true
  copy:
    src: ~/project/backend.tar.gz
    dest: /home/ubuntu/backend.tar.gz

- name: Start PM2
  shell: |
    cd /home/ubuntu/
    tar xzvf backend.tar.gz
    cd backend
    sudo npm install -g npm@latest
    sudo npm install -g webpack-dev-server
    sudo npm install
    sudo npm run build
    sudo pm2 start npm --name backend -- start
# ---
# - name: "upgrade packages"
#   become: yes
#   apt:
#     upgrade: "yes"


# - name: "Copy backend tar.gz file and unzipping it"
#   become: yes
#   unarchive:
#     src: ~/project/backend.tar.gz
#     dest: /home/ubuntu

# - name: "run migration"
#   become: yes
#   shell: npm install -g npm@latest

# - name: "installing dependencies"
#   become: yes
#   npm:
#     path: /home/ubuntu/backend

# - name: "NPM install"
#   become: yes
#   command: npm install
#   args:
#     chdir: /home/ubuntu/backend

# # - name: "Npm I - Install dependencies"
# #   become: true
# #   command: npm install
# #   args:
# #     chdir: /home/ubuntu/backend

# - name: "Run Migration"
#   become: true
#   shell: npm run migrations
#   args:
#     chdir: /home/ubuntu/backend

# - name: "Start pm2"
#   become: true
#   shell: pm2 start --name "backend" npm -- start
#   args:
#     chdir: /home/ubuntu/backend